runtime: nodejs18
service: avalability-client
handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client
    secure: always
    http_headers:
      Strict-Transport-Security: 'max-age=63072000; includeSubDomains; preload'
  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt)$
    secure: always
    http_headers:
      Strict-Transport-Security: 'max-age=63072000; includeSubDomains; preload'
  - url: /.*
    script: auto
    secure: always
env_variables:
  HOST: '0.0.0.0'
automatic_scaling:
  max_pending_latency: 15s
inbound_services:
- warmup
